#!/usr/bin/env bun
import { parseArgs } from "util";
import { existsSync, mkdirSync } from "fs";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

// A.15.1 U.Work Generator
// Usage: bun log-work.ts --spec <MethodId> --role <RoleAssigning> --context <Ctx> --action <Description>

const { values } = parseArgs({
  args: Bun.argv,
  options: {
    spec: { type: "string" },
    role: { type: "string" },
    context: { type: "string" },
    action: { type: "string" },
  },
  strict: true,
  allowPositionals: true,
});

if (!values.spec || !values.role || !values.context || !values.action) {
  console.error("Usage: log-work --spec <id> --role <assigned> --context <ctx> --action <desc>");
  process.exit(1);
}

/**
 * Validates an input value against a pattern or exits with a message.
 */
function requireMatch(value: string | undefined, pattern: RegExp, name: string, description: string): string {
  const trimmed = (value ?? "").trim();
  if (trimmed.length === 0 || !pattern.test(trimmed)) {
    console.error(`Invalid ${name} '${value ?? ""}'. Expected ${description}.`);
    process.exit(1);
  }
  return trimmed;
}

type PosthogEvent = {
  spec: string;
  role: string;
  context: string;
  action: string;
  timestamp: string;
};

/**
 * Emits a PostHog event when configured via environment variables.
 */
async function emitPosthogEvent(event: PosthogEvent): Promise<void> {
  const apiKey = process.env.POSTHOG_API_KEY?.trim();
  const distinctId = process.env.POSTHOG_DISTINCT_ID?.trim();
  if (!apiKey || !distinctId) {
    return;
  }

  const host = (process.env.POSTHOG_HOST ?? "https://app.posthog.com").trim();
  let url: URL;
  try {
    url = new URL("/capture", host);
  } catch {
    console.warn(`WARN: Invalid POSTHOG_HOST '${host}'.`);
    return;
  }

  const includeAction = process.env.POSTHOG_INCLUDE_ACTION === "1";
  const properties: Record<string, unknown> = {
    spec: event.spec,
    role: event.role,
    context: event.context,
    action_length: event.action.length,
    action_included: includeAction,
  };
  if (includeAction) {
    properties.action = event.action;
  }

  const payload = JSON.stringify({
    api_key: apiKey,
    event: "u_work_logged",
    distinct_id: distinctId,
    properties,
    timestamp: event.timestamp,
  });

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 2000);

  try {
    const response = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: payload,
      signal: controller.signal,
    });
    if (!response.ok) {
      console.warn(`WARN: PostHog capture failed (${response.status}).`);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`WARN: PostHog capture failed (${message}).`);
  } finally {
    clearTimeout(timeout);
  }
}

const context = requireMatch(values.context, /^[A-Za-z0-9][A-Za-z0-9_-]*$/, "context", "a safe path segment (letters, digits, '_' or '-')");

// 1. Target: runtime/contexts/[Ctx]/telemetry/work/
const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, "../../../../../");
const targetDir = join(repoRoot, "runtime", "contexts", context, "telemetry", "work");

if (!existsSync(targetDir)) {
  mkdirSync(targetDir, { recursive: true });
}

// 2. Format: [Timestamp]-[Spec]-[Role].md (hashed or simplified)
const now = new Date();
const isoTimestamp = now.toISOString();
const timestamp = isoTimestamp.replace(/[:.]/g, "-");
const filename = `work-${timestamp}.md`;
const filePath = join(targetDir, filename);

if (existsSync(filePath)) {
  console.error(`Error: Work record already exists at ${filePath}`);
  process.exit(1);
}

// 3. Content: A.15.1 U.Work Record
const content = `---
type: U.Work
spec: ${values.spec}
performer: ${values.role}
context: ${context}
timestamp_start: ${isoTimestamp}
---

# U.Work: Execution of ${values.spec}

## 1. Anchors
- **Spec**: \`${values.spec}\`
- **Performer**: \`${values.role}\`
- **Context**: \`${context}\`

## 2. Occurrence
${values.action}

## 3. Evidence
- **Trace**: Generated by \`telemetry/log-work\`
`;

await Bun.write(filePath, content);
await emitPosthogEvent({
  spec: values.spec,
  role: values.role,
  context,
  action: values.action,
  timestamp: isoTimestamp,
});
console.log(`Work Logged: ${filePath}`);
